### ISSUE TITLE
自定义 CSS 样式或者添加默认的样式 

### ISSUE THREAD

**Issue by songouyang** [wafer-li/hexo-filter-plantuml#4]
MathJax 有默认样式会居中显示。https://github.com/stevenjoezhang/hexo-filter-mathjax

![image](https://user-images.githubusercontent.com/16632254/72170739-5fd0e900-340c-11ea-81db-bef8dae02839.png)

**Comment by miao1007** [comment]
For customized css, please add css in your theme's css

```styl
  img {
    max-width: 90%
    display: block
  }
```
